// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vydfyfhndunxxcfgbzje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5ZGZ5ZmhuZHVueHhjZmdiemplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzc5MjUsImV4cCI6MjA2NTgxMzkyNX0.PnBJsA4LKZO0QAFX1T8_Ps23HxLf2jj2OGuNrdUWZRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);